---
title: "Untitled"
author: "Reuben"
date: "2024-12-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Packages
```{r}
library(MOFA2)
library(tidyverse)
```


#load best MOFA model
```{r}
model<- load_model(file.path(getwd(), paste0("MOFA_model_15.hdf5")))
```

#Convert GMT file into a binary format that MOFA can use to perform GSEA
```{r}

# Read the GMT file
gmt_file <- "h.all.v2024.1.Hs.symbols.gmt"

# Read the file into a list
gmt_list <- readLines(gmt_file)

# Initialize an empty list to hold the gene sets
genesets <- list()
geneset_names <- c()

# Extract gene sets and their names - getting gene set into format the the later steps can use
for (line in gmt_list) {
  parts <- strsplit(line, "\t")[[1]]
  geneset_name <- parts[1]
  genes <- parts[-(1:2)] # Skip the first two elements (name and description)
  genesets[[geneset_name]] <- genes
  geneset_names <- c(geneset_names, geneset_name)
}

# Get the unique gene names across all gene sets
all_genes <- unique(unlist(genesets))

# Initialize the gene matrix
gene_matrix <- matrix(0, 
                      nrow = length(genesets), 
                      ncol = length(all_genes), 
                      dimnames = list(geneset_names, all_genes))

# Populate the matrix with 1 if the gene is part of the gene set
for (geneset_name in names(genesets)) {
  gene_matrix[geneset_name, genesets[[geneset_name]]] <- 1
}
dim(gene_matrix)

```

```{r}
# run_enrichmet expects a gene set matrix of binary values 
# perform a positive gene set enrichment on the important factors
enrichment.results_pos <- run_enrichment(model,
  view = "RNA", factors = c(2,4,5,12),
  feature.sets = gene_matrix,
  sign = "positive",
  statistical.test = "parametric"
)
# perform a negative gene set enrichment on the important factors
enrichment.results_neg <- run_enrichment(model,
  view = "RNA", factors = c(2,4,5,12),
  feature.sets = gene_matrix,
  sign = "negative",
  statistical.test = "parametric"
)
```

```{r}
# plot a heatmap of the enrichment scores for each geneset and print out the adjusted p values
# for pos enrichment 
plot_enrichment_heatmap(enrichment.results_pos)
pos_enriched <- enrichment.results_pos$pval.adj[]
# for neg enrichment
plot_enrichment_heatmap(enrichment.results_neg)
neg_enriched <- enrichment.results_neg$pval.adj[]

enrichment.results_pos$sigPathways
```

#save enrichment scores in csv files - supplementary material
```{r}
write.csv(pos_enriched,file='positive_GSEA.csv', row.names=TRUE)
write.csv(neg_enriched,file='negative_GSEA.csv', row.names=TRUE)
```


```{r}
# plot the genesets that were enriched along with the -log adjusted p values,
# setting a adj-pval threshold of 0.05 represented by a line.
# plot the two enriched factors in the positive instance
plot_enrichment(enrichment.results_pos, 
  factor = 1, 
  max.pathways = 25,alpha = 0.05
  
)


plot_enrichment(enrichment.results_pos, 
  factor = 2, 
  max.pathways = 25,alpha = 0.05
  
)



plot_enrichment(enrichment.results_pos, 
  factor = 4, 
  max.pathways = 25,alpha = 0.05
  
)

# plot the enriched factor in the negative instance


plot_enrichment(enrichment.results_neg, 
  factor = 2, 
  max.pathways = 25,alpha = 0.05
  
)

plot_enrichment(enrichment.results_neg, 
  factor = 3, 
  max.pathways = 25,alpha = 0.05
  
)

```

```{r}
# repeating the previous code chunk but printing a more detailed output of the genesets.
# This highlights what genes have high weightings in the mofa model that are found in an enriched genesets.
plot_enrichment_detailed(enrichment.results_pos, 
  factor = 1, 
  max.genes = 8, 
  max.pathways = 20, alpha = 0.05
)
plot_enrichment_detailed(enrichment.results_pos, 
  factor = 2, 
  max.genes = 8, 
  max.pathways = 20, alpha = 0.05
)
plot_enrichment_detailed(enrichment.results_pos, 
  factor = 4, 
  max.genes = 8, 
  max.pathways = 20, alpha = 0.05
)

plot_enrichment_detailed(enrichment.results_neg, 
  factor = 2, 
  max.genes = 8, 
  max.pathways = 20, alpha = 0.05
)
plot_enrichment_detailed(enrichment.results_neg, 
  factor = 3, 
  max.genes = 8, 
  max.pathways = 20, alpha = 0.05
)
```






